// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7AMupLrEK02wX17Qw9dIVsFrceV_-bU',
    appId: '1:913616998470:web:32ead38d3e42fe21f5ba47',
    messagingSenderId: '913616998470',
    projectId: 'dp-flutter-project',
    authDomain: 'dp-flutter-project.firebaseapp.com',
    storageBucket: 'dp-flutter-project.appspot.com',
    measurementId: 'G-ZY4RH6P48F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunssxLxGF-agGEbHox7O8r6tRQO_5sls',
    appId: '1:913616998470:android:a4200ea828f2a7b9f5ba47',
    messagingSenderId: '913616998470',
    projectId: 'dp-flutter-project',
    storageBucket: 'dp-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjnTmqZL1yrr6hgCSZaNdC2fwepGC_oK4',
    appId: '1:913616998470:ios:c86ca6a8219e341af5ba47',
    messagingSenderId: '913616998470',
    projectId: 'dp-flutter-project',
    storageBucket: 'dp-flutter-project.appspot.com',
    iosClientId: '913616998470-7tamna1lh96e5jk7j3i0cbs7ho1mibvf.apps.googleusercontent.com',
    iosBundleId: 'com.flutterApp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjnTmqZL1yrr6hgCSZaNdC2fwepGC_oK4',
    appId: '1:913616998470:ios:c86ca6a8219e341af5ba47',
    messagingSenderId: '913616998470',
    projectId: 'dp-flutter-project',
    storageBucket: 'dp-flutter-project.appspot.com',
    iosClientId: '913616998470-7tamna1lh96e5jk7j3i0cbs7ho1mibvf.apps.googleusercontent.com',
    iosBundleId: 'com.flutterApp.mynotes',
  );
}
